Disable Groovy version check in Spock also in GroovyShell
To prevent:
IncompatibleGroovyVersionException: The Spock compiler plugin cannot execute because ...

in tests with GroovyShell.